# Build stage
 FROM node:25.1-alpine3.21

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

# Add .env for CRA to inline
COPY tsconfig.json  ./
COPY .env.production ./.env

COPY public ./public
COPY src ./src

RUN yarn build



# Step 2: Serve the React app using NGINX
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port that NGINX will run on
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
